### PR TITLE
Fix the Illegal character encoder issue for repo name

### PR DESCRIPTION
**Pull request by yma96**
See https://issues.redhat.com/browse/MMENG-4156

### CODE REVIEW

**Comment by sswguo** [comment]
Will this impact the generic proxy repo query ? I remembered we make encoder for that repo, just confirm. @ruhan1

**Comment by ruhan1** [comment]
> Will this impact the generic proxy repo query ? I remembered we make encoder for that repo, just confirm. @ruhan1

I guess not. generic proxy does not use indy-client. However, should Indy allow spaces in the repo name? I wonder some others places may break if we allow such.

**Comment by sswguo** [comment]
> I guess not. generic proxy does not use indy-client. However, should Indy allow spaces in the repo name? I wonder some others places may break if we allow such.

if so, that does not block this PR, we may need to add input validation for repo creation. 

LGTM.

**Comment by yma96** [comment]
Ok, I'll merge this first.

**Pull request merged**
